apiVersion: v1
kind: Pod
metadata:
  name: text-gen-pod
  namespace: default
  labels:
    app: text-gen
spec:
  containers:
  - name: text-gen-container
    image: larkinwc/text-generation-webui-k8s:cuda
    imagePullPolicy: Always
    ports:
    - containerPort: 5000
    - containerPort: 5001
    - containerPort: 5005
    - containerPort: 7860
    env:
    - name: TORCH_CUDA_ARCH_LIST
      value: "7.5"
    volumeMounts:
    - name: text-gen-pvc
      mountPath: /app/loras
      subPath: loras
    - name: text-gen-pvc
      mountPath: /app/models
      subPath: models
    resources:
      limits:
        nvidia.com/gpu: 2  # requesting 1 GPU
  tolerations:
  - key: "nvidia.com/gpu"
    operator: "Exists"
    effect: "NoSchedule"
  volumes:
  - name: text-gen-pvc
    persistentVolumeClaim:
      claimName: text-gen-pvc