apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: text-gen-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard